// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/odysseia.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PtolemaiosClient is the client API for Ptolemaios service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PtolemaiosClient interface {
	// Get the config from ptolemaios
	GetSecret(ctx context.Context, in *VaultRequest, opts ...grpc.CallOption) (*ElasticConfigVault, error)
}

type ptolemaiosClient struct {
	cc grpc.ClientConnInterface
}

func NewPtolemaiosClient(cc grpc.ClientConnInterface) PtolemaiosClient {
	return &ptolemaiosClient{cc}
}

func (c *ptolemaiosClient) GetSecret(ctx context.Context, in *VaultRequest, opts ...grpc.CallOption) (*ElasticConfigVault, error) {
	out := new(ElasticConfigVault)
	err := c.cc.Invoke(ctx, "/proto.Ptolemaios/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PtolemaiosServer is the server API for Ptolemaios service.
// All implementations must embed UnimplementedPtolemaiosServer
// for forward compatibility
type PtolemaiosServer interface {
	// Get the config from ptolemaios
	GetSecret(context.Context, *VaultRequest) (*ElasticConfigVault, error)
	mustEmbedUnimplementedPtolemaiosServer()
}

// UnimplementedPtolemaiosServer must be embedded to have forward compatible implementations.
type UnimplementedPtolemaiosServer struct {
}

func (UnimplementedPtolemaiosServer) GetSecret(context.Context, *VaultRequest) (*ElasticConfigVault, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedPtolemaiosServer) mustEmbedUnimplementedPtolemaiosServer() {}

// UnsafePtolemaiosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtolemaiosServer will
// result in compilation errors.
type UnsafePtolemaiosServer interface {
	mustEmbedUnimplementedPtolemaiosServer()
}

func RegisterPtolemaiosServer(s grpc.ServiceRegistrar, srv PtolemaiosServer) {
	s.RegisterService(&Ptolemaios_ServiceDesc, srv)
}

func _Ptolemaios_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtolemaiosServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ptolemaios/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtolemaiosServer).GetSecret(ctx, req.(*VaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ptolemaios_ServiceDesc is the grpc.ServiceDesc for Ptolemaios service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ptolemaios_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Ptolemaios",
	HandlerType: (*PtolemaiosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _Ptolemaios_GetSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/odysseia.proto",
}
