// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/odysseia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VaultRequest) Reset() {
	*x = VaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_odysseia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultRequest) ProtoMessage() {}

func (x *VaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_odysseia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultRequest.ProtoReflect.Descriptor instead.
func (*VaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_odysseia_proto_rawDescGZIP(), []int{0}
}

// The response message with the config taken from vault
type ElasticConfigVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElasticUsername string `protobuf:"bytes,1,opt,name=elasticUsername,proto3" json:"elasticUsername,omitempty"`
	ElasticPassword string `protobuf:"bytes,2,opt,name=elasticPassword,proto3" json:"elasticPassword,omitempty"`
	ElasticCERT     string `protobuf:"bytes,3,opt,name=ElasticCERT,proto3" json:"ElasticCERT,omitempty"`
}

func (x *ElasticConfigVault) Reset() {
	*x = ElasticConfigVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_odysseia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElasticConfigVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticConfigVault) ProtoMessage() {}

func (x *ElasticConfigVault) ProtoReflect() protoreflect.Message {
	mi := &file_proto_odysseia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticConfigVault.ProtoReflect.Descriptor instead.
func (*ElasticConfigVault) Descriptor() ([]byte, []int) {
	return file_proto_odysseia_proto_rawDescGZIP(), []int{1}
}

func (x *ElasticConfigVault) GetElasticUsername() string {
	if x != nil {
		return x.ElasticUsername
	}
	return ""
}

func (x *ElasticConfigVault) GetElasticPassword() string {
	if x != nil {
		return x.ElasticPassword
	}
	return ""
}

func (x *ElasticConfigVault) GetElasticCERT() string {
	if x != nil {
		return x.ElasticCERT
	}
	return ""
}

var File_proto_odysseia_proto protoreflect.FileDescriptor

var file_proto_odysseia_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x64, 0x79, 0x73, 0x73, 0x65, 0x69, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a,
	0x0c, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8a, 0x01,
	0x0a, 0x12, 0x45, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65,
	0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6c, 0x61, 0x73,
	0x74, 0x69, 0x63, 0x43, 0x45, 0x52, 0x54, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45,
	0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x43, 0x45, 0x52, 0x54, 0x32, 0x4b, 0x0a, 0x0a, 0x50, 0x74,
	0x6f, 0x6c, 0x65, 0x6d, 0x61, 0x69, 0x6f, 0x73, 0x12, 0x3d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x79, 0x73, 0x73, 0x65, 0x69, 0x61, 0x2d, 0x67,
	0x72, 0x65, 0x65, 0x6b, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_odysseia_proto_rawDescOnce sync.Once
	file_proto_odysseia_proto_rawDescData = file_proto_odysseia_proto_rawDesc
)

func file_proto_odysseia_proto_rawDescGZIP() []byte {
	file_proto_odysseia_proto_rawDescOnce.Do(func() {
		file_proto_odysseia_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_odysseia_proto_rawDescData)
	})
	return file_proto_odysseia_proto_rawDescData
}

var file_proto_odysseia_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_odysseia_proto_goTypes = []interface{}{
	(*VaultRequest)(nil),       // 0: proto.VaultRequest
	(*ElasticConfigVault)(nil), // 1: proto.ElasticConfigVault
}
var file_proto_odysseia_proto_depIdxs = []int32{
	0, // 0: proto.Ptolemaios.GetSecret:input_type -> proto.VaultRequest
	1, // 1: proto.Ptolemaios.GetSecret:output_type -> proto.ElasticConfigVault
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_odysseia_proto_init() }
func file_proto_odysseia_proto_init() {
	if File_proto_odysseia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_odysseia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_odysseia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElasticConfigVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_odysseia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_odysseia_proto_goTypes,
		DependencyIndexes: file_proto_odysseia_proto_depIdxs,
		MessageInfos:      file_proto_odysseia_proto_msgTypes,
	}.Build()
	File_proto_odysseia_proto = out.File
	file_proto_odysseia_proto_rawDesc = nil
	file_proto_odysseia_proto_goTypes = nil
	file_proto_odysseia_proto_depIdxs = nil
}
